#!/usr/bin/env python3

import csv
import uuid
import mysql.connector
from mysql.connector import errorcode

# ---------- 1. Connect to MySQL server ----------
def connect_db():
        try:
                    connection = mysql.connector.connect(
                                        host="localhost",
                                                    user="root",
                                                                password="your_password"  # Replace with your MySQL root password
                                                                        )
                            return connection
                            except mysql.connector.Error as err:
                                        print(f"Error connecting to MySQL: {err}")
                                                exit(1)

                                                # ---------- 2. Create database ----------
                                                def create_database(connection):
                                                        cursor = connection.cursor()
                                                            try:
                                                                        cursor.execute("CREATE DATABASE IF NOT EXISTS ALX_prodev")
                                                                                print("✅ Database 'ALX_prodev' is ready.")
                                                                                    except mysql.connector.Error as err:
                                                                                                print(f"Failed creating database: {err}")
                                                                                                    finally:
                                                                                                                cursor.close()

                                                                                                                # ---------- 3. Connect to ALX_prodev database ----------
                                                                                                                def connect_to_prodev():
                                                                                                                        try:
                                                                                                                                    connection = mysql.connector.connect(
                                                                                                                                                        host="localhost",
                                                                                                                                                                    user="root",
                                                                                                                                                                                password="your_password",  # Replace with your MySQL root password
                                                                                                                                                                                            database="ALX_prodev"
                                                                                                                                                                                                    )
                                                                                                                                            return connection
                                                                                                                                            except mysql.connector.Error as err:
                                                                                                                                                        print(f"Error connecting to ALX_prodev: {err}")
                                                                                                                                                                exit(1)

                                                                                                                                                                # ---------- 4. Create user_data table ----------
                                                                                                                                                                def create_table(connection):
                                                                                                                                                                        cursor = connection.cursor()
                                                                                                                                                                            create_query = """
                                                                                                                                                                                CREATE TABLE IF NOT EXISTS user_data (
                                                                                                                                                                                        user_id CHAR(36) PRIMARY KEY,
                                                                                                                                                                                                name VARCHAR(255) NOT NULL,
                                                                                                                                                                                                        email VARCHAR(255) NOT NULL,
                                                                                                                                                                                                                age DECIMAL(3, 0) NOT NULL,
                                                                                                                                                                                                                        INDEX (user_id)
                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                cursor.execute(create_query)
                                                                                                                                                                                                                                                        print("✅ Table 'user_data' is ready.")
                                                                                                                                                                                                                                                            except mysql.connector.Error as err:
                                                                                                                                                                                                                                                                        print(f"Failed creating table: {err}")
                                                                                                                                                                                                                                                                            finally:
                                                                                                                                                                                                                                                                                        cursor.close()

                                                                                                                                                                                                                                                                                        # ---------- 5. Insert data ----------
                                                                                                                                                                                                                                                                                        def insert_data(connection, data):
                                                                                                                                                                                                                                                                                                cursor = connection.cursor()
                                                                                                                                                                                                                                                                                                    insert_query = """
                                                                                                                                                                                                                                                                                                        INSERT INTO user_data (user_id, name, email, age)
                                                                                                                                                                                                                                                                                                            VALUES (%s, %s, %s, %s)
                                                                                                                                                                                                                                                                                                                ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email), age=VALUES(age)
                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                    for row in data:
                                                                                                                                                                                                                                                                                                                                                    user_id = str(uuid.uuid4())
                                                                                                                                                                                                                                                                                                                                                                cursor.execute(insert_query, (user_id, row['name'], row['email'], row['age']))
                                                                                                                                                                                                                                                                                                                                                                        connection.commit()
                                                                                                                                                                                                                                                                                                                                                                                print(f"✅ Inserted {cursor.rowcount} rows.")
                                                                                                                                                                                                                                                                                                                                                                                    except mysql.connector.Error as err:
                                                                                                                                                                                                                                                                                                                                                                                                print(f"Insert failed: {err}")
                                                                                                                                                                                                                                                                                                                                                                                                    finally:
                                                                                                                                                                                                                                                                                                                                                                                                                cursor.close()

                                                                                                                                                                                                                                                                                                                                                                                                                # ---------- 6. Read CSV ----------
                                                                                                                                                                                                                                                                                                                                                                                                                def read_csv(filepath):
                                                                                                                                                                                                                                                                                                                                                                                                                        with open(filepath, newline='') as csvfile:
                                                                                                                                                                                                                                                                                                                                                                                                                                    reader = csv.DictReader(csvfile)
                                                                                                                                                                                                                                                                                                                                                                                                                                            return [row for row in reader]

                                                                                                                                                                                                                                                                                                                                                                                                                                        # ---------- MAIN ----------
                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                conn = connect_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                    create_database(conn)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn_prodev = connect_to_prodev()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                create_table(conn_prodev)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user_data = read_csv("user_data.csv")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        insert_data(conn_prodev, user_data)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn_prodev.close()

